spring:
  application:
    name: chat
  data:
    mongodb:
      host: localhost
      port: 27018
      username: root
      password: testpassword1234
      database: mongodb
      authentication-database: admin
      authSource: admin
      repositories:
        enabled: true

    redis:
      host: localhost
      port: 6379
      password: testpassword1234

    redis:
      host: localhost
      port: 6379
      password: testpassword1234

server:
  port: 8081

auth:
  url: "http://localhost:30001/"
url:
  server: "http://localhost:8080/"

page:
  size: 100
chatroom:
  expiration: 1d
  baseurl: "http://localhost:8081/"
