spring:
  application:
    name: chat
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: 58155815
      database: mongodb
      authentication-database: admin

server:
  port: 8081

auth:
  url: "http://localhost:8080/"
page:
  size: 100
