spring:
  profiles:
    active: ${APPLICATION_PROFILE:local}
  application:
    name: user
  datasource:
    username: root
    password: 2435800
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kpring
  jpa:
    hibernate:
      ddl-auto: update

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080}

server:
  port: 8081
