spring:
  application:
    name: server
  datasource:
    username: root
    password: 2435800
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kpring

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080}
