spring:
  application:
    name: server
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: test1234@
      database: mongodb
      authentication-database: admin

auth:
  url: ${AUTH_SERVICE_URL:http://localhost:8080}
