apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Release.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auth.port }}
      protocol: TCP
  selector:
    app: {{ .Values.auth.name }}
