{{- if .Values.enable.auth }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Release.namespace }}
spec:
  {{- if eq .Values.profile "local" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}

  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
      protocol: TCP
      {{- if eq .Values.profile "local" }}
      nodePort: {{ .Values.auth.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.auth.name }}
{{- end }}
