name: CI

on:
  push:
    branches: [ main ] # push 되었을 때, 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # jdk 21 환경 구성
      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: make api documents
        run: ./gradlew --info openapi3

      - name: push image using jib
        run: ./gradlew --info jib

  tagging:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: checkout infra repository
        uses: actions/checkout@v4
        with:
          repository: kSideProject/kpring-infra
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: main

      - name: edit infra repository tag
        run: |
          echo 'env(IMAGE_TAG)'
          yq eval -i '.service.tag = env(IMAGE_TAG)' ./charts/server/values.yaml
          yq eval -i '.service.tag = env(IMAGE_TAG)' ./charts/user/values.yaml
          yq eval -i '.service.tag = env(IMAGE_TAG)' ./charts/auth/values.yaml

      - name: commit
        uses: leigholiver/commit-with-deploy-key@v1.0.4
        with:
          source: .
          destination_repo: kSideProject/kpring-infra
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          commit_message: 'ci: update tag to env(IMAGE_TAG)'
